### Dependencies

In [1]:
# Import dependencies
import pandas as pd
import numpy as np
import os

pd.set_option('display.max_columns', None)

## Set working directory to tree_growth_metaanalysis_snmc
os.chdir('../../')

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/global/software/rocky-8.x86_64/manual/modules/langs/anaconda3/2024.02-1/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/global/software/rocky-8.x86_64/manual/modules/langs/anaconda3/2024.02-1/lib/python3.11/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/global/software/rocky-8.x86_64/manual/modules/langs/anaconda3/2024.02-1/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 701, in start
    self.io_loop.start()
  File "/global/home/users/jessicakatz/.local/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/global/software/rocky-8.x86_64/manual/modules/langs/anaconda3/2024.02-1/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/global/software/rocky-8.x86_64/manual/modules/langs/anaconda3/2024.02-1/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/global/software/rocky-8.x86_64/manual/modules/langs/anaconda3/2024.02-1/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/global/software/rocky-8.x86_64/manual/modules/langs/anaconda3/2024.02-1/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "/global/software/rocky-8.x86_64/manual/modules/langs/anaconda3/2024.02-1/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "/global/software/rocky-8.x86_64/manual/modules/langs/anaconda3/2024.02-1/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 429, in dispatch_shell
    await result
  File "/global/software/rocky-8.x86_64/manual/modules/langs/anaconda3/2024.02-1/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/global/software/rocky-8.x86_64/manual/modules/langs/anaconda3/2024.02-1/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "/global/software/rocky-8.x86_64/manual/modules/langs/anaconda3/2024.02-1/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/global/home/users/jessicakatz/.local/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3046, in run_cell
    result = self._run_cell(
  File "/global/home/users/jessicakatz/.local/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3101, in _run_cell
    result = runner(coro)
  File "/global/home/users/jessicakatz/.local/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/global/home/users/jessicakatz/.local/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3306, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/global/home/users/jessicakatz/.local/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3488, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/global/home/users/jessicakatz/.local/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3548, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_1074711/1311215073.py", line 2, in <module>
    import pandas as pd
  File "/global/home/users/jessicakatz/.local/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/global/home/users/jessicakatz/.local/lib/python3.11/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/global/home/users/jessicakatz/.local/lib/python3.11/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/global/home/users/jessicakatz/.local/lib/python3.11/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/global/home/users/jessicakatz/.local/lib/python3.11/site-packages/pandas/core/arrays/arrow/array.py", line 50, in <module>
    from pandas.core import (
  File "/global/home/users/jessicakatz/.local/lib/python3.11/site-packages/pandas/core/ops/__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "/global/home/users/jessicakatz/.local/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "/global/home/users/jessicakatz/.local/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/global/home/users/jessicakatz/.local/lib/python3.11/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/global/home/users/jessicakatz/.local/lib/python3.11/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/global/software/rocky-8.x86_64/manual/modules/langs/anaconda3/2024.02-1/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/global/software/rocky-8.x86_64/manual/modules/langs/anaconda3/2024.02-1/lib/python3.11/site-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

In [2]:
## Metaregressor file directory
mr_dir = 'Covariate_and_metaregressor_processing/Processed_data/'

In [3]:
## List of sites
site_list = ['Blodgett', 'LaTour', 'Sequoia', 'STEF', 'Teakettle', 'TharpsCreek', 'WLakeTahoe']

## Climate metaregressors

In [4]:
### Load climate metaregressors processed via create_climate_metaregressors
clim = pd.read_csv('{}Climate/site_mean_clim.csv'.format(mr_dir))
clim

,Site,ppt_by_waterYr,tmax_by_waterYr,cwd_by_waterYr,pdsi_by_waterYr
0,Blodgett,959.96050,27.728548,542.30030,-0.319073
1,LaTour,695.89700,24.285917,484.53226,-0.671427
2,STEF,599.03130,25.354880,705.64520,-1.640567
3,Sequoia,452.98000,21.914751,698.84830,-2.146069
4,Teakettle,570.52940,23.081861,742.97253,-1.041993
5,TharpsCreek,508.32254,22.714918,743.24835,-0.911075
6,WLakeTahoe,571.57776,23.189638,594.39307,-1.135433

## Soil metaregressors

In [5]:
### Load soil metaregressors processed via create_soil_metaregressors
soils = pd.read_csv('{}Soil/unit_mean_soil.csv'.format(mr_dir))

## Make Teakettle unit names lowercase
soils.loc[soils['Site']=='Teakettle', 'UnitID'] = soils.loc[soils['Site']=='Teakettle', 'UnitID'].str.lower()

soils

,PlotID,Latitude,Longitude,Site,UnitID,UniqueID,geometry,TotalDepth,CEC_50cm,ksat_50cm,AWC_50cm
0,FFS7CONTROL,36.581771,-118.762344,Sequoia,FFS7CONTROL,Sequoia_FFS_FFS7CONTROL,POLYGON ((-118.76288784879824 36.5813156249320...,191.836735,14.350000,72.216429,0.105510
1,FFS5BURN,36.585279,-118.754700,Sequoia,FFS5BURN,Sequoia_FFS_FFS5BURN,POLYGON ((-118.75524390655013 36.5848243815964...,163.842105,59.566105,89.193895,0.102211
2,FFS6BURN,36.585635,-118.759024,Sequoia,FFS6BURN,Sequoia_FFS_FFS6BURN,POLYGON ((-118.75955386424457 36.5851925225764...,190.000000,12.728947,67.866842,0.107895
3,FFS2BURN,36.595484,-118.746431,Sequoia,FFS2BURN,Sequoia_FFS_FFS2BURN,POLYGON ((-118.74697366335567 36.5950301035425...,167.252084,62.210854,94.133642,0.097012
4,LOTHAR,36.562389,-118.741997,TharpsCreek,LOTHAR,Sequoia_Tharp_LOTHAR,POLYGON ((-118.7425685192587 36.56191098240621...,191.836735,14.350000,72.216429,0.105510
...,...,...,...,...,...,...,...,...,...,...,...
89,20,38.180488,-119.986097,STEF,20,STEF-VDT_20,POLYGON ((-119.98715867012244 38.1801368552789...,145.571429,17.797143,11.848571,0.131429
90,21,38.180718,-119.983347,STEF,21,STEF-VDT_21,POLYGON ((-119.98398241599054 38.1806327952951...,145.571429,17.797143,11.848571,0.131429
91,22,38.178893,-119.985330,STEF,22,STEF-VDT_22,POLYGON ((-119.98562211270271 38.1785089780963...,145.571429,17.797143,11.848571,0.131429
92,23,38.177163,-119.984951,STEF,23,STEF-VDT_23,POLYGON ((-119.98561048114323 38.1768745805550...,145.571429,17.797143,11.848571,0.131429
93,24,38.178492,-119.982811,STEF,24,STEF-VDT_24,POLYGON ((-119.98342601732472 38.1778882523550...,123.285714,13.500000,18.500000,0.120000

## Relative stand density index

In [6]:
## Compile rSDI for all sites
rsdi = pd.DataFrame()

for site in site_list:
    temp = pd.read_csv(mr_dir + 'Stand_structure/{}_rsdi.csv'.format(site))
    temp['Site'] = site
    rsdi = pd.concat([rsdi, temp])

## Make UnitID a string
rsdi['UnitID'] = rsdi['UnitID'].astype(str)

rsdi

         UnitID      SDI_in      maxSDI      rSDI        Site
0            40  385.646057  552.042904  0.698580    Blodgett
1            60  259.352256  552.042904  0.469805    Blodgett
2           180  198.950363  552.042904  0.360389    Blodgett
3           190  271.782735  552.042904  0.492322    Blodgett
4           240  371.302079  552.042904  0.672596    Blodgett
..          ...         ...         ...       ...         ...
3       TWC 3 T  182.117458  644.267296  0.282674  WLakeTahoe
4   WRD 20-16 C  391.648981  644.267296  0.607898  WLakeTahoe
5   WRD 20-16 T  402.604632  644.267296  0.624903  WLakeTahoe
6    WRD 20-9 C  334.961622  644.267296  0.519911  WLakeTahoe
7    WRD 20-9 T  172.689772  644.267296  0.268041  WLakeTahoe

[94 rows x 5 columns]

## Treatment intensity

In [7]:
## Compile treatment intensity for all sites
intensity = pd.DataFrame()

for site in site_list:
    temp = pd.read_csv(mr_dir + 'Stand_structure/{}_intensity.csv'.format(site))
    temp['Site'] = site
    intensity = pd.concat([intensity, temp])

## Replace NaN treatment with "None"
intensity.loc[intensity['Treatment'].isnull(), 'Treatment'] = 'None'

## Make UnitID a string
intensity['UnitID'] = intensity['UnitID'].astype(str)

## Replace null intensities with 0
intensity.loc[intensity['BA_reduction'].isnull(), 'BA_reduction'] = 0

intensity

         UnitID  Treatment  BA_reduction        Site
0            40       None     -2.604808    Blodgett
1            60       Burn      2.176369    Blodgett
2           180  Burn+Thin     23.107300    Blodgett
3           190       Thin     12.928511    Blodgett
4           240       None     -4.091529    Blodgett
..          ...        ...           ...         ...
3       TWC 3 T       Thin     28.374367  WLakeTahoe
4   WRD 20-16 C       None      0.838978  WLakeTahoe
5   WRD 20-16 T       Thin      7.806518  WLakeTahoe
6    WRD 20-9 C       None      6.186546  WLakeTahoe
7    WRD 20-9 T       Thin     39.303998  WLakeTahoe

[94 rows x 4 columns]

# Merge metaregressors

In [8]:
## Merge climate and soil
all_rgrs = pd.merge(soils[['Site', 'UnitID', 'TotalDepth', 'CEC_50cm', 'ksat_50cm', 'AWC_50cm']],
                    clim,
                    how = 'outer',
                    on = 'Site')

## Merge with rSDI
all_rgrs = pd.merge(all_rgrs, 
                    rsdi[['Site', 'UnitID', 'rSDI']],
                   how = 'outer',
                   on = ['Site', 'UnitID'])

## Merge with intensity
all_rgrs = pd.merge(all_rgrs,
                    intensity,
                   how = 'outer',
                   on = ['Site', 'UnitID'])

all_rgrs

,Site,UnitID,TotalDepth,CEC_50cm,ksat_50cm,AWC_50cm,ppt_by_waterYr,tmax_by_waterYr,cwd_by_waterYr,pdsi_by_waterYr,rSDI,Treatment,BA_reduction
0,Blodgett,180,155.520508,23.352415,9.000000,0.153066,959.96050,27.728548,542.30030,-0.319073,0.360389,Burn+Thin,23.107300
1,Blodgett,190,160.464628,13.702465,13.379279,0.143866,959.96050,27.728548,542.30030,-0.319073,0.492322,Thin,12.928511
2,Blodgett,240,164.488564,13.436419,9.000000,0.160000,959.96050,27.728548,542.30030,-0.319073,0.672596,None,-4.091529
3,Blodgett,340,162.089165,13.288813,14.369534,0.156038,959.96050,27.728548,542.30030,-0.319073,0.518709,Burn,0.127643
4,Blodgett,350,158.990333,13.994643,15.925788,0.134484,959.96050,27.728548,542.30030,-0.319073,0.443884,Thin,28.032620
...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,WLakeTahoe,TWC 3 T,193.493320,22.708957,96.626990,0.148829,571.57776,23.189638,594.39307,-1.135433,0.282674,Thin,28.374367
90,WLakeTahoe,WRD 20-16 C,199.370000,19.381800,87.058000,0.199000,571.57776,23.189638,594.39307,-1.135433,0.607898,None,0.838978
91,WLakeTahoe,WRD 20-16 T,198.270000,19.659300,84.871200,0.203200,571.57776,23.189638,594.39307,-1.135433,0.624903,Thin,7.806518
92,WLakeTahoe,WRD 20-9 C,197.482969,19.746960,84.373035,0.203161,571.57776,23.189638,594.39307,-1.135433,0.519911,None,6.186546
93,WLakeTahoe,WRD 20-9 T,198.270000,19.659300,84.871200,0.203200,571.57776,23.189638,594.39307,-1.135433,0.268041,Thin,39.303998

In [9]:
## Save
all_rgrs.to_csv(mr_dir + 'all_regressors_by_unit.csv',
               index = False)